baseURL: "https://wijk.works"
title: Wijk Works - En webbyrå. Helt enkelt.
paginate: 5
theme: hugo-PaperMod
copyright: "&copy; 2020 Wijk Works AB"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpored: false

minify:
  disableXML: true
  minifyOutput: true

Menus:
  main:
    - URL: services/
      Name: Tjänster
      Weight: 1
    - URL: about/
      Name: Om Oss
      Weight: 2
    - URL: jobs/
      Name: Jobb
      Weight: 3
    - URL: contact/
      Name: Kontakt
      Weight: 4

params:
  env: production
  title: Wijk Works
  description: En webbyrå. Helt enkelt.

  images:
    - "apple-touch-icon.png"

  ShowReadingTime: false
  ShowShareButtons: false
  comments: false
  defaultTheme: auto
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "favicon.png"

  label:
    text: "En webbyrå. Helt enkelt."

  profileMode:
    enabled: true
    title: Wijk Works_
    subtitle: "Vad behöver du hjälp med?"
    buttons:
      - name: Hemsida
        url: "/services/#hemsida"
      - name: App
        url: "/services/#app"
      - name: Annat
        url: "/services/#annat"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/company/wijk-works/"
    - name: github
      url: "https://github.com/wijk-works/"
    - name: email
      url: "mailto:hello@wijk.works"
