name: main

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Install dependencies
      run: |
        curl -L https://github.com/gohugoio/hugo/releases/download/v0.84.4/hugo_0.84.4_Linux-64bit.tar.gz -o hugo.tar.gz
        tar -xvf hugo.tar.gz
        cp themes/hugo-theme-tailwindcss-starter/package.json themes/hugo-theme-tailwindcss-starter/package-lock.json .
        npm i

    - name: Build site
      run: ./hugo --minify

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to S3
      run: aws s3 sync public/. s3://${{ secrets.S3_BUCKET_NAME }}/  --delete

    - name: Clear CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
